### ISSUE TITLE
Remoto?

### ISSUE THREAD

**Issue by heigler** [vivadecora/backend-teste#1]
Achei o teste através de uma post no telegram, não ficou claro se é presencial em SP ou se estão aceitando remoto, fiquei interessado em fazer o teste.
Grande abraço,

**Comment by teles** [comment]
Olá, @heigler.
A vaga é apenas presencial para SP.
Mas corrigimos os testes enviados mesmo que não estejam disponíveis para a vaga na equipe.
Confirma, @taciogt ?

**Comment by taciogt** [comment]
Confirmo, @teles. @heigler, se quiser fazer o teste, nós estamos dispostos a corrigir e lhe enviar o feedback com a nossa opinião. Se você participar do processo seletivo para a vaga e chegar a etapa da entrevista técnica, nós conversaremos pessoalmente sobre o teste.
Abraços,

**Comment by heigler** [comment]
@teles @taciogt show de bola, obrigado pela informação!
