### ISSUE TITLE
Resolução do Teste

### ISSUE THREAD

**Issue by Bernardoow** [vivadecora/backend-teste#3]
https://github.com/Bernardoow/vivadecora_backend_teste

**Comment by taciogt** [comment]
Oi @Bernardoow,
Pode mandar teu perfil do LinkedIn ou número de celular para contato?

**Comment by Bernardoow** [comment]
Olá @taciogt , boa tarde!

Claro que posso. Segue:
LinkedIn: https://www.linkedin.com/in/bernardo-gomes-de-abreu-a8a36432
Telefone: 991940893
