### ISSUE TITLE
Resolução do Teste

### ISSUE THREAD

**Issue by carlosmaniero** [vivadecora/backend-teste#6]
Eu estou mandando o teste adiantado, mesmo sem ter concluído tudo, pois estou com medo de perder o time da vaga. 

Enfim, eu estou demorando um pouco a mais pra desenvolver, pois eu tive uma grande preocupação em pensar na melhor arquitetura para resolver o problema e não só resolver o problema. Todo o ambiente foi projetado em Docker. Ela possui os seguintes containers:
- Ngnix (que servirá o front)
- Celery
- Aplicação Django
- Load Balancer da Aplicação (sim! é possível escalonar mais containers de aplicação)
- Postgres
- ElasticSearch

É só mandar tudo pra Amazon que funciona. rs

Eu faço tudo usando integração contínua, então o travis-ci está configurado na minha aplicação e sempre faz o build dela e valida os testes.

A parte da busca é realizada pelo elasticsearch e todos os veículos são indexados em background utilizando Celery. 

A comunicação como ElasticSearch é realizada via requests. Eu não quis utilizar as bíbliotecas mais Pythonicas para realizar esse trabalho, justamenta para ter um ambiente com mais testes e testes mais úteis. 

Eu preciso fechar:
- Alguns detalhes da API de busca
- Criar fixtures
- Fazer o Front

A parte do back-end eu termino ainda hoje. O front, eu consigo entregar até segunda, no máxmo terça.

Segue repositório: https://github.com/carlosmaniero/docker-spa
Segue também meu Linkedin: https://www.linkedin.com/in/carlosmaniero

Assim que eu concluir, eu atualizo a issue.

Ps: Tem alguns repositórios interessandes no meu github ;)
Dá uma olhada no pygamii.

Abraços!

**Comment by teles** [comment]
Obrigado, @carlosmaniero. 
Quando estiver ok pode mandar, se conseguir entregar até segunda está dentro do nosso tempo para avaliação.
Abraço

cc @taciogt

**Comment by teles** [comment]
PS: seu perfil do linkedin está com link errado.

**Comment by carlosmaniero** [comment]
Estranho, aqui abriu certinho. Segue novamente:

https://br.linkedin.com/in/carlosmaniero

**Comment by teles** [comment]
Agora ambos os links abriram, valeu @carlosmaniero !! :D

**Comment by carlosmaniero** [comment]
Fala @teles! 
Eu atualizei o repositório! Infelizmente, para entregar hoje, eu não consegui fazer tudo o que eu queria.
Das coisas que ficaram faltando que eu queria melhorar:

1 - É maior cobertura de testes 86% é baixo. Eu não tive tempo para cobrir a busca de testes.
2 - Fazer o container dos arquivos estáticos executar o Gulp. Hoje eu estou versionando a pasta public. Não gosto de fazer isso.
3 - A busca dava pra deixar ainda mais inteligente.

Mas é isso ai! Espero que gostem!
