### ISSUE TITLE
Resolução do teste

### ISSUE THREAD

**Issue by drudi** [vivadecora/backend-teste#9]
Olá,

Segue o link para meu repositório com a solução: https://github.com/drudi/backend-chalenge

Não finalizei a parte do frontend ainda, pois tive alguns problemas de compatibilidade do django 1.10 com a app django-cors-headers, e isso me tomou um bom tempo para resolver (detalhes, no README do projeto).

Acredito que eu consiga terminar até amanhã no final do dia, ou no máximo na quarta-feira, caso vocês aceitem a solução até lá.

Abraços,
Drudi

**Comment by IuryAlves** [comment]
Obrigado @drudi. Vamos aguardar até quarta então.

**Comment by drudi** [comment]
Olá Iury,

Terminei o frontend e o desafio. Não me preocupei com gráficos ou UX, mesmo porque não conseguiria a tempo.

Qualquer dúvida, estou à disposição.

Abraços,
Drudi

**Comment by IuryAlves** [comment]
Obrigado @drudi . Estamos avaliando.
